-- =============================================================================
-- V1 - Estrutura inicial: cidades e medições de indicadores ESG
-- =============================================================================

CREATE TABLE cidade (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(120) NOT NULL,
    uf            VARCHAR(2)   NOT NULL,
    populacao     INTEGER      NOT NULL CHECK (populacao > 0),
    criado_em     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    atualizado_em TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- não permite a mesma cidade duas vezes na mesma UF (sem diferenciar maiúsculas/minúsculas)
CREATE UNIQUE INDEX uk_cidade_nome_uf ON cidade (lower(nome), uf);

CREATE TABLE indicador_esg (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cidade_id       BIGINT        NOT NULL REFERENCES cidade (id) ON DELETE CASCADE,
    tipo            VARCHAR(40)   NOT NULL,
    valor           NUMERIC(14,4) NOT NULL CHECK (valor >= 0),
    data_referencia DATE          NOT NULL,
    fonte           VARCHAR(200),
    criado_em       TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- acelera a busca da medição mais recente de cada indicador por cidade
CREATE INDEX idx_indicador_cidade_tipo_data ON indicador_esg (cidade_id, tipo, data_referencia DESC);
